### ISSUE TITLE
Edge Processing

### ISSUE THREAD

**Issue by phvass** [ros-industrial-attic/godel#110]
- [x] `Create edge detection procedure for captured clouds`
- [x] `Develop edge detection planner`
- [x] `GUI integration of edge-processor`

**Comment by Jmeyer1292** [comment]
With #123 and subsequent PRs we have made a lot of progress toward this goal.

We still need:
 - Edge inspection routines
 - GUI integration (into the simple-gui?)
 - Some refinements to edge joint planning to control for things like the density of boundary points, noise in the data, and any process adjustments (such as a tool angle) we might need.

**Comment by phvass** [comment]
Edge inspection is not in-scope for the M4 FTP. Simple-GUI integration is already captured in issue #158.
