### ISSUE TITLE
Fixed Orientation of Surface Normals and Edge Normals

### ISSUE THREAD

**Issue by Jmeyer1292** [ros-industrial-attic/godel#134]
Poses generated as waypoints for the robot tool currently have a "forced" common normal. For handling sloping surfaces, this is clearly not ideal.

Normals were forced to deal with noise in the data that caused unpleasant robot motion.

**Comment by phvass** [comment]
@woodaaron to submit a PR for this

**Comment by woodaaron** [comment]
For edges, I believe this issue was corrected as part of pull request #153.
