### ISSUE TITLE
Add exclusion zone to ABB robot code

### ISSUE THREAD

**Issue by phvass** [ros-industrial-attic/godel#186]

**Comment by Levi-Armstrong** [comment]
A wiki has been created showing how to create ABB Work Zones [here](https://github.com/ros-industrial-consortium/godel/wiki/Create-ABB-Work-Zones).

**Comment by phvass** [comment]
Now that the cell is hooked up, can @Levi-Armstrong add the zones?

**Comment by phvass** [comment]
@Jmeyer1292 to implement today
