### ISSUE TITLE
Blocking service calls should be converted to actions

### ISSUE THREAD

**Issue by woodaaron** [ros-industrial-attic/godel#195]
In particular, the blend process executor will block if we request it wait for execution to complete. If it blocks, we are unable to watch the robot model operate on the piece. If we do not wait for execution we have no feedback on when the process is complete (from a code perspective; we can still watch it on the model).

**Comment by phvass** [comment]
Austin to review and merge.

**Comment by Jmeyer1292** [comment]
Addressed (for planning at least) in https://github.com/ros-industrial-consortium/godel/pull/200
