### ISSUE TITLE
Add license text to header

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/godel#2]
Every source/header file should have the proper license text.  For this project, Apache 2.0 should be the default license.

**Comment by jrgnicho** [comment]
+1

**Comment by dpsolomon** [comment]
I think my code is OK, and from what I can tell Jorge's is as well. @jrgnicho Do you know of any source code that still has this issue?

**Comment by dpsolomon** [comment]
Pretty sure this is all taken care of
