### ISSUE TITLE
mesh importer throws an assertion failure when it receives surfaces produced from surface detection 

### ISSUE THREAD

**Issue by jrgnicho** [ros-industrial-attic/godel#20]
After the process path request is sent to the surface_detection_server node from the gui, the following assertion message is shown:
Failed to find match for field 'intensity'.

```
[FATAL] [1402033017.120979648]: ASSERTION FAILED
    file = /home/coky/ros/hydro/catkin_ws/src/godel/godel_process_path_generation/src/mesh_importer.cpp
    line = 118
    cond = std::abs(plane_pt(2)) < .001

[ INFO] [1402033017.228714881]: process plan request sent
```

After this error the entire node exits.  
In order to reproduce this error run the following in a terminal

```
roslaunch godel_surface_detection robot_blending.launch
```

This will bring up rviz with the blending widget already running.  
Next, set the desired number of scans with the "Number of scans" numeric indicator to a number greater than 1 and then click "Scan and Find". The robot will move to each scan pose and the gui will be disable until the surfaces detection process finishes

If one or more surfaces are found then there will be a plane mesh marker overlaid on the point cloud patch corresponding to it.  In the select tab, click "select all" in order to select all the surface or only select the desired surface in the 3d rviz viewer.  Then click "Generate Paths".

Go back to the terminal from which the launch file was run in order to see the error message.

**Comment by dpsolomon** [comment]
Fixed in pull request #23
