### ISSUE TITLE
Holes on the triangulated surface meshes

### ISSUE THREAD

**Issue by jrgnicho** [ros-industrial-attic/godel#21]
The current triangulation method (greedy triangulation) produces triangulated surfaces with one or more holes.

**Comment by jrgnicho** [comment]
The changes introduced by PR #34 momentarily address this issue by computing the convex hull of the surfaces prior to triangulation. This allows the process path generator node to generate paths since it now receives well behaved meshes; It would crash otherwise. The problem with this approach is that the convex hull approximation discards features of interest in the part that should be taken into account for generating paths that reflect the true geometry of the part.  Once an adequate triangulation technique is implemented the Convex hull step needs to be removed.

**Comment by Jmeyer1292** [comment]
Changes made in the integration with Milestone 3 code (see #93) have introduced a new method of triangulation that does not suffer from holes. However, we have not removed the convex hull operation to match. That will be addressed in a separate issue.
