### ISSUE TITLE
Installation Instructions missing

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/godel#32]
Could we add installation instructions to the main readme?  Simply downloading the git repo results in:

```
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find OpenVoronoi (missing: OpenVoronoi_LIBRARY
  OpenVoronoi_INCLUDE_DIR)
```

**Comment by dpsolomon** [comment]
There are detailed instructions in the individual packages readme files. These could be copied into the main readme, but I think they should just be referenced because it's more likely they will get updated in the package readme then at the top level.

**Comment by shaun-edwards** [comment]
Done.  Updated references in 00d6b880058865338269a7cc6eccec50171c6494
