### ISSUE TITLE
Provide suitably patched & build openvoronoi pkgs

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial-attic/godel#33]
Just an idea: seeing as the versions in the Ubuntu repositories cannot be used, you might consider releasing a version that does work, and set it as a system dependency of the packages. Such a version could then also already include the patch to `offset_sorter.hpp`. It's also nicer to not circumvent the package manager on a lot of distributions, even if things end up in `/usr/local/`.

There are some options for this:
1. fork upstream (perhaps as a repo under `ros-industrial-consortium`), patch it, build as non-catkin package in normal catkin workspace (so everything still from source)
2. release as [3rd-party non-catkin pkg](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty) into ROS release (fi: `ros-hydro-openvoronoi-something-something`). Patching could be part of build process, and iiuc, forking would not even strictly be necessary (just a release repository)
3. fork it, patch it, but do this on an Ubuntu PPA. Advantage: gets build 'automatically' for different distros, and is a bit more common practice. Disadvantage: users would have to setup the PPA before installing the godel project (but they currently have to build something from source)
4. get upstream patched and re-released into different distros. Not sure if feasible (frozen releases, etc), but would mean everything (at least for Ubuntu) would work as it should

Options 1, 2 & 3 would require some maintenance effort, as upstream has to be tracked. 1, 2 & 3 are rather Ubuntu focused also (although catkin can now also generate RPMs).

Option 2 seems pretty doable to me, as patching and releasing do not impact the upstream repository.

**Comment by shaun-edwards** [comment]
I'll let @phvass determine the priority.  I think one of these options should be the end goal of milestone 2.  This would make it very easy download/install the FIRST ever completed ROS-I FTP. ;)

**Comment by gavanderhoorn** [comment]
If newer versions of `openvoronoi` are actually usable (and have been released in newer (> 12.04) versions of Ubuntu), using `backportpackage` might be an easy way to produce a backported deb. See [backportpackage - helper to test package backports](http://manpages.ubuntu.com/manpages/precise/man1/backportpackage.1.html) for the manpage, and [How to backport packages on Ubuntu Linux](http://opensourcehacker.com/2013/03/20/how-to-backport-packages-on-ubuntu-linux/) for a blog post with some information on the usage of the tool.

**Comment by gavanderhoorn** [comment]
These repositories might also be interesting:
- [ethz-asl/ceres_catkin](https://github.com/ethz-asl/ceres_catkin)
- [ethz-asl/suitesparse](https://github.com/ethz-asl/suitesparse)
- [ethz-asl/glog_catkin](https://github.com/ethz-asl/glog_catkin)
- [ethz-asl/gflags_catkin](https://github.com/ethz-asl/gflags_catkin)

Although these are catkin wrappers, as opposed to a system wide installation of Ceres cs.

**Comment by gavanderhoorn** [comment]
I think option 2 makes the most sense for now, perhaps even as a `ros-hydro-godel-openvoronoi`. As soon as upstream is fixed / patched / updated the dependency can be changed to the upstream release (provided the needed `rosdep` rules exist).

**Comment by shaun-edwards** [comment]
Is there a chance that newer versions in `indigo`/`14.04` can be more easily deployed?

**Comment by gavanderhoorn** [comment]
I don't see how 14.04 will help here: the [PPA](https://launchpad.net/~anders-e-e-wallin/+archive/ubuntu/cam) only has pkgs up to Quantal. In addition, they are lagging behind the github repo. I cannot find an `openvoronoi` package in the official Trusty repositories (or for any Ubuntu version).

Option 2 allows one to checkout godel from source and a single `catkin_make` will build everything. If released, the `ros-DISTRO-godel-openvoronoi` package would just be 'another deb' to install. It would also avoid clashing with a system installed `openvoronoi`.

I don't see 4 happening, and 3 would need users of godel to add a PPA to their system (although setting up ROS requires users to add a repository in a similar way, so this would just be one additional step).

**Comment by gavanderhoorn** [comment]
Submitted `rosdep` rules for `libqd-dev` in ros/rosdistro#6599.

**Comment by gavanderhoorn** [comment]
@phvass: is this something we want to fix? There are several options, all of which are (imho) preferable to manually downloading and building `openvoronoi`.

**Comment by phvass** [comment]
Gijs, If you see things in Godel that need fixing, feel free to proceed up to your 8hr limit/week. Thanks!
Paul

**Comment by gavanderhoorn** [comment]
@gavanderhoorn wrote:

> I think option 2 makes the most sense for now, perhaps even as a `ros-hydro-godel-openvoronoi`. As soon as upstream is fixed / patched / updated the dependency can be changed to the upstream release (provided the needed `rosdep` rules exist).

Opted for a 5th option: fork `openvoronoi`, add minimal `package.xml` and replacement `CMakeLists.txt`, then make relevant packages in `godel` depend on `godel_openvoronoi` (the wrapped `openvoronoi` project). See [gavanderhoorn/godel_openvoronoi/hydro-devel](https://github.com/gavanderhoorn/godel_openvoronoi/tree/hydro-devel) and [gavanderhoorn/godel/depend_on_wrapped_openvoronoi_pkg](https://github.com/gavanderhoorn/godel/tree/depend_on_wrapped_openvoronoi_pkg).

While this adds some maintenance overhead (as upstream changes are no longer automatically tracked), it does put Godel maintainers in full control over whether (and when) updates to `openvoronoi` are imported into the Godel project (as upstream changes are no longer automatically tracked), preventing possibly breaking changes to `openvoronoi` from destabilising Godel.

Tracking upstream is relatively easy: just rebase the wrapper branch after importing upstream.

To test:

```
git clone -b depend_on_wrapped_openvoronoi_pkg https://github.com/gavanderhoorn/godel.git
git clone -b hydro-devel https://github.com/gavanderhoorn/godel_openvoronoi.git
```

Then a normal build.

No need to install `openvoronoi` from `aewallin/openvoronoi`.

**Comment by gavanderhoorn** [comment]
Opinions?

**Comment by shaun-edwards** [comment]
+1 to forking. Can we capture the update procedure in the README?

On Monday, February 23, 2015, G.A. vd. Hoorn notifications@github.com
wrote:

> Opinions?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-industrial-consortium/godel/issues/33#issuecomment-75642866
> .

## 

Sent from Gmail Mobile

**Comment by gavanderhoorn** [comment]
> Can we capture the update procedure in the README?

Sure.

I'll submit a PR.

**Comment by gavanderhoorn** [comment]
Btw: I didn't want to go for option 2 (release as [3rd-party non-catkin pkg](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty)), as a (I think) project-specific patch is applied to `openvoronoi`, and I wouldn't like to release a non-upstream version of `openvoronoi` as a ROS pkg then.

**Comment by gavanderhoorn** [comment]
I think this can be closed when #49 has been merged.

**Comment by jrgnicho** [comment]
+1 for closing after merging #49

**Comment by gavanderhoorn** [comment]
Closing this, as #49 has been merged.
