### ISSUE TITLE
Update installation instructions for indigo

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial-attic/godel#58]
Related: #53

`motoman` and `industrial_core` packages have not been released to `indigo`.
When trying to compile godel with ros-indigo these packages are missing.

Manually cloning the two packages in the cartkin workspace solves the problem.

**Comment by Jmeyer1292** [comment]
I believe that `industrial_core` has now been released on Indigo. We have addressed the `motoman` issues in #71.

Is this okay to close?
