### ISSUE TITLE
Convex Hull of Surfaces

### ISSUE THREAD

**Issue by Jmeyer1292** [ros-industrial-attic/godel#96]
Per discussion in #21, at some point a convex hull operation was added to all candidate surfaces in order to improve meshing. Later pull-requests have fixed meshing, but the convex hulls remain. For parts with concave features, this can lead to the tool dropping right off of the surface.

**Comment by phvass** [comment]
Intend to assign to Alex Goins

**Comment by phvass** [comment]
Will be closed when #111 is merged
