### ISSUE TITLE
Indigo  rosdep error when execute rosdep install --from-paths . --ignore-src

### ISSUE THREAD

**Issue by chenchengshao** [ros-industrial-attic/godel#97]
Version: unbutu 14.04 trusty   Indigo ROS system.
Command: `rosdep install --from-paths . --ignore-src`

Return:

```
WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
godel_robot_resources: Cannot locate rosdep definition for [industrial_extrinsic_cal]
```

**Comment by Jmeyer1292** [comment]
Thanks for bringing this to my attention, I'll add the appropriate dependency on industrial_extrinsic_cal. In the mean-time, if you clone the`indigo-devel` branch of [this repo](https://github.com/ros-industrial/industrial_calibration.git), you should be able to make progress.

**Comment by Jmeyer1292** [comment]
@chenchengshao We have elected to forgo the dependency on industrial calibration at the moment to ease the installation process for those just getting into the project. See #98.

Please let us know if you have more issues.

**Comment by chenchengshao** [comment]
Thank you Jmeyer1292, I already tried to use rosdep install -r --from-paths . --ignore-src to ignore this error and also install the abb separately, it should have the same result as the new solution you posted.
