### ISSUE TITLE
Missing line in CMakeLists.txt causes packages to not build with catkin tools.

### ISSUE THREAD

**Issue by jettan** [ros-industrial-attic/godel#99]
Offending files are:

```
godel_robots/abb/godel_irb2400/godel_irb2400_support/CMakeLists.txt
godel_robots/godel_robot_resources/CMakeLists.txt
```

The missing line:

```
find_package(catkin REQUIRED)
```

**Comment by jettan** [comment]
Still missing the line in godel_robots/godel_robot_resources/CMakeLists.txt

**Comment by gavanderhoorn** [comment]
Pretty sure I added it [here](https://github.com/ros-industrial-consortium/godel/blob/4d3025dd974ad48a05cd1575d6e8ad096be9b2d0/godel_robots/godel_robot_resources/CMakeLists.txt#L4) (via 4d3025dd).

**Comment by jettan** [comment]
Ah,  my bad then. Didn't see it since 5321918 didn't mention it.

**Comment by gavanderhoorn** [comment]
I opted to fix each file in a separate commit. So that's why.

**Comment by gavanderhoorn** [comment]
Thanks for reporting btw.
